services:
  - type: web
    name: csv-to-json-api
    env: node
    buildCommand: |
      npm install
      npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "5001"
